# Relative paths to every UI configuration file.
# To extend the UI (teaching it about additional formats or specs)
# add new configuration. All of these will be loaded.
manifest:
- config/default.yml
