# config.yml
trees:
  - path: /
    tree: tiled.examples.generated_minimal:tree
uvicorn:
  host: 0.0.0.0
  port: 8000
authentication:
  providers:
  - provider: test
    authenticator: tiled.authenticators:DictionaryAuthenticator
    args:
      users_to_passwords:
        alice: PASSWORD
  secret_keys:
    - SECRET
