# config.yml
trees:
  - path: /
    tree: tiled.examples.generated_minimal:tree
uvicorn:
  host: 0.0.0.0
  port: 8000
database:
  uri: /tmp/tiled_database.sqlite  # This is not actually created by test.
authentication:
  allow_anonymous_access: true
  providers:
  - provider: test
    authenticator: tiled.authenticators:DictionaryAuthenticator
    args:
      users_to_passwords:
        alice: PASSWORD
  secret_keys:
    - SECRET
