services:

  ldap:
    image: nfrastack/openldap:2.6-alpine
    ports:
      - '389:1389'
      - '636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - ADMIN_PASS=adminpassword
      - ENABLE_BACKUP=False
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2

  #TODO: This product is leaving open-source container distribution
  # Find a new image or product to use
  # https://github.com/minio/minio/issues/21647#issuecomment-3418675115
  minio:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    # volumes:
    #   - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address :9001
    restart: unless-stopped

  create-bucket:
    image: minio/mc:latest
    environment:
      MC_HOST_minio: http://minioadmin:minioadmin@minio:9000
    entrypoint:
      - sh
      - -c
      - |
        until mc ls minio > /dev/null 2>&1; do
          sleep 0.5
        done

        mc mb --ignore-existing minio/buck
  
  postgres:
    image: docker.io/library/postgres:16-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tiled-example-data
    volumes:
      - ./scripts/postgres.sh:/docker-entrypoint-initdb.d/postgres.sh

  redis:
    image: docker.io/redis:7-alpine
    ports:
      - 6379:6379