api_url: /api/v1
structure_families:
  array:
    formats:
      - mimetype: text/csv
        display_name: CSV
        extension: .csv
      - mimetype: text/plain
        display_name: Text
        extension: .txt
      - mimetype: image/png
        display_name: PNG image
        extension: .png
      - mimetype: image/tiff
        display_name: TIFF image
        extension: .tiff
      - mimetype: application/json
        display_name: JSON
        extension: .json
      - mimetype: application/json-seq
        display_name: JSON Lines
        extension: .jsonl
      - mimetype: text/html
        display_name: HTML
        extension: .html
      - mimetype: application/octet-stream
        display_name: C-ordered array
        extension: ""
  table:
    formats:
      - mimetype: text/csv
        display_name: CSV
        extension: .csv
      - mimetype: text/plain
        display_name: Text
        extension: .txt
      - mimetype: application/vnd.apache.arrow.file
        display_name: Apache Arrow
        extension: ""
      - mimetype: application/x-parquet
        display_name: Parquet
        extension: .parquet
      - mimetype: application/json
        display_name: JSON
        extension: .json
      - mimetype: application/json-seq
        display_name: JSON Lines
        extension: .jsonl
      - mimetype: text/html
        display_name: HTML
        extension: .html
      - mimetype: application/x-hdf5
        display_name: HDF5
        extension: .h5
  node:
    formats:
      - mimetype: application/x-hdf5
        display_name: HDF5
        extension: .h5
