# config.yml
trees:
  - path: /
    tree: tiled.adapters.files:DirectoryAdapter.from_directory
    args:
      directory: "example_files"
uvicorn:
  host: 0.0.0.0
  port: 8000
authentication:
  allow_anonymous_access: true
  providers:
  - provider: test
    authenticator: tiled.authenticators:DictionaryAuthenticator
    args:
      users_to_passwords:
        alice: PASSWORD
    secret_keys:
      - SECRET
